# -*- mode: ruby -*-
# vi: set ft=ruby :
require './hostname'
include MyVars

Vagrant.configure("2") do |config|

	config.vm.define :frontend do |machine|

		machine.vm.box_url 	= "http://repo.searchmetrics.com/VirtualAppliance/baseboxes/base-ubuntu-server-12.04.box"
		machine.vm.box 		= "base-ubuntu-server-12.04"

		# Add a host only network to use with avahi w/o the need for port forwarding
		# we have to set a static ip to be able to use nfs synced folders
		machine.vm.network :private_network, { :ip =>  '172.28.128.2' }
		#machine.vm.network "public_network"

		# set hostname
		machine.vm.hostname = "frontend"
		#machine.vm.hostname = DHCPVMNAME # unique hostname and ip

		# virtual box customizations
		config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", 2048, "--natdnshostresolver1", "on"]
			# allow symlinks in this folder
			vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app-data", 1]
		end

		machine.vm.synced_folder "~/Development/Sources/scripts/www", "/var/www/info", { :nfs => !Vagrant::Util::Platform.windows? }
		machine.vm.synced_folder "~/Development/Sources/suite7", "/var/www/app", { :nfs => !Vagrant::Util::Platform.windows?, :id => 'app-data' }
		machine.vm.synced_folder "~/Development/Sources/library/php", "/var/www/lib", { :nfs => !Vagrant::Util::Platform.windows? }
		machine.vm.synced_folder "~/Development/Sources/tools", "/var/www/tools", { :nfs => !Vagrant::Util::Platform.windows? }

		machine.vm.provision :puppet_server do |puppet|
			# local puppet server for puppet development
			#puppet.puppet_server = "puppet.local"
			puppet.puppet_server = "puppet01-seo-search.unbelievable-machine.net"
			puppet.puppet_node = "frontend.local"
			puppet.options = "--onetime --no-daemonize --logdest console --environment development  --no-report"
			# use this if only any unexpected behaviour occurs
			#puppet.options = "--verbose --debug --onetime --no-daemonize --logdest console --environment development "
		end
		
		
		#machine.vm.provision :puppet do |puppet|
		#	puppet.module_path = "../../../puppetmaster/src/modules"
		#	# mount the nodes folder to also have access to shared manifests
		#	puppet.manifests_path = "../../../puppetmaster/src/manifests/nodes"
		#	# include the environment in the manifest file name
		#	puppet.manifest_file = "development/frontend.local.pp"
		#	# use this if only any unexpected behaviour occurs
		#	#puppet.options = "--verbose --debug"
		#end		

	end

end